definitions:
  models.ActionsData:
    properties:
      action_type:
        type: integer
      area_id:
        type: string
      is_playing:
        type: integer
      user_token:
        type: string
    type: object
  models.ReactionsReceived:
    properties:
      area_id:
        type: string
      reaction_type:
        type: integer
      user_token:
        type: string
    type: object
  models.TriggerdModels:
    properties:
      area_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /access-token:
    post:
      consumes:
      - application/json
      description: Send the code received by the frontend to get the Spotify access-token
        of the user
      produces:
      - application/json
      responses:
        "200":
          description: the code to redirect to
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get
      tags:
      - Spotify OAUTH2
  /actions:
    get:
      consumes:
      - application/json
      description: Get Actions from Spotify
      produces:
      - application/json
      responses:
        "200":
          description: Reactions name with parameters of it as object
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Actions from Spotify
      tags:
      - Actions Spotify
    post:
      consumes:
      - application/json
      description: Post an Spotify actions, receive by the Message Brocker (handler
        of communication between services) and register it to him database
      parameters:
      - description: It contains the Area Id, the location and the Spotify of the
          Area
        in: body
        name: routes
        required: true
        schema:
          $ref: '#/definitions/models.ActionsData'
      produces:
      - application/json
      responses:
        "200":
          description: Response is the Id of the Area
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post an Actions
      tags:
      - Actions Date Spotify services
  /callback:
    get:
      consumes:
      - application/json
      description: Send the code received by Spotify to the frontend
      produces:
      - application/json
      responses:
        "200":
          description: the code to redirect to
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send the code received by Spotify to the frontend
      tags:
      - Spotify OAUTH2
  /oauth:
    get:
      consumes:
      - application/json
      description: Send the url to redirect to for the OAUTH2 Spotify
      produces:
      - application/json
      responses:
        "200":
          description: the URL to redirect to for the OAUTH2 Spotify
          schema:
            type: string
      summary: Send the url to redirect to for the OAUTH2 Spotify
      tags:
      - Spotify OAUTH2
  /reaction:
    post:
      consumes:
      - application/json
      description: Register the reactions received by the message brocker with all
        informations nedded
      parameters:
      - description: It must contains the AreaId and the reactions type
        in: body
        name: routes
        required: true
        schema:
          $ref: '#/definitions/models.ReactionsReceived'
      produces:
      - application/json
      responses:
        "200":
          description: Response is the received data
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register an received Reactions
      tags:
      - Spotify Area
  /reactions:
    get:
      consumes:
      - application/json
      description: send all the reactions available on the Spotify services as an
        object arrays with the names and the object needed
      produces:
      - application/json
      responses:
        "200":
          description: Response is the received data
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: send all the reactions
      tags:
      - Spotify Area
  /trigger:
    post:
      consumes:
      - application/json
      description: Actions triggerd the reactions and call the trigger route
      parameters:
      - description: It contains the Area Id to the reactions
        in: body
        name: routes
        required: true
        schema:
          $ref: '#/definitions/models.TriggerdModels'
      produces:
      - application/json
      responses:
        "200":
          description: Response of the reactions
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error it contains the error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Trigger an Area
      tags:
      - Spotify trigger
swagger: "2.0"
