##
## EPITECH PROJECT, 2025
## AREA
## File description:
## Makefile
##

tests_run:
	cd Meteo/routes && go test -cover
	cd DateTimeServices/routes && go test -cover
	cd CryptoMoney/routes && go test -cover
