FROM golang:alpine

WORKDIR /app

COPY . /app

# RUN go install github.com/cespare/reflex@latest
# RUN go build -o time-services .

EXPOSE 8082

CMD go run main.go
# CMD reflex -r '\.go$' -s go run main.go
# CMD ./time-services
