version: '3.8'

services:
  frontend:
    build: Frontend
    container_name: frontend
    environment:
      PORT: 3000
    ports:
      - 3000:3000

  api-gateway:
    build: Backend/ApiGateway
    container_name: api-gateway
    environment:
      PORT: 8080
      USER_API: http://user-services:8081/
      TIME_API: http://time-services:8082/
      DISCORD_API: http://discord:8083/
    ports:
      - 8080:8080

  message-brocker:
    build: Backend/MessageBrocker
    container_name: message-brocker
    ports:
      - 8084:8084

  user-services:
    build: Backend/Services/UserServices
    container_name: user-services
    environment: 
      PORT: 8081
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@user-services-db:5432/user
      SECRET_KEY: PET
    ports:
      - 8081:8081
    depends_on:
      - user-services-db

  user-services-db:
    build: Backend/Services/UserServices/Database
    container_name: user-services-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - 5432:5432
    restart: always

  time-services:
    build: Backend/Services/DateTimeServices
    container_name: time-services
    environment:
      PORT: 8082
      API_GATEWAY: http://api-gateway:8080/
      DATE_TIME_API: http://worldtimeapi.org/api/timezone/Etc/UTC
      DB: postgresql://root:password@time-services-db:5433/time
    ports:
      - 8082:8082
    depends_on:
      - time-services-db

  time-services-db:
    build: Backend/Services/DateTimeServices/Database
    container_name: time-services-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: time
    ports:
      - 5433:5433
    restart: always

  discord:
    build: Backend/Services/Discord
    container_name: discord
    environment:
      PORT: 8083
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@discord-db:5434/discord
      CLIENT_ID: 1313077002005385236
      CLIENT_SECRET: Ku7K2lQYvws_L-xp7ialrt11weriVHyk
      REDIRECT_WEB: http://localhost:8083/callback
      REDIRECT_MOBILE: http://localhost:8083/mobile-callback
    ports:
      - 8083:8083
    depends_on:
      - discord-db

  discord-db:
    build: Backend/Services/Discord/Database
    container_name: discord-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discord
    ports:
      - 5434:5434
    restart: always
