version: '3.8'

services:
  frontend:
    build: Frontend
    container_name: frontend
    environment:
      PORT: 8081
    ports:
      - 8081:8081

  api-gateway:
    build: Backend/ApiGateway
    container_name: api-gateway
    environment:
      PORT: 8080
      USER_API: http://user-services:8085/
      TIME_API: http://time-services:8082/
      DISCORD_API: http://discord:8083/
    ports:
      - 8080:8080

  message-brocker:
    build: Backend/MessageBrocker
    container_name: message-brocker
    environment:
      USER_API: http://user-services:8085/
      TIME_API: http://time-services:8082/
      DISCORD_API: http://discord:8083/
    ports:
      - 8084:8084

  user-services:
    build: Backend/Services/UserServices
    container_name: user-services
    environment: 
      PORT: 8085
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8085:8085
    depends_on:
      - area-db

  blue-sky:
    build: Backend/Services/BlueSky
    container_name: blue-sky
    environment:
      PORT: 8096
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8096:8096
    depends_on:
      - area-db

  github:
    build: Backend/Services/Github
    container_name: github
    environment:
      PORT: 8086
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8086:8086
    depends_on:
      - area-db

  gitlab:
    build: Backend/Services/Gitlab
    container_name: gitlab
    environment:
      PORT: 8087
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8087:8087
    depends_on:
      - area-db

  google:
    build: Backend/Services/Google
    container_name: google
    environment:
      PORT: 8088
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8088:8088
    depends_on:
      - area-db

  meteo:
    build: Backend/Services/Meteo
    container_name: meteo
    environment:
      PORT: 8090
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8089:8089
    depends_on:
      - area-db

  miro:
    build: Backend/Services/Miro
    container_name: miro
    environment:
      PORT: 8090
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8090:8090
    depends_on:
      - area-db

  spotify:
    build: Backend/Services/Spotify
    container_name: spotify
    environment:
      PORT: 8091
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8091:8091
    depends_on:
      - area-db

  steam:
    build: Backend/Services/Steam
    container_name: steam
    environment: 
      PORT: 8092
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8092:8092
    depends_on:
      - area-db

  ticket-master:
    build: Backend/Services/TicketMaster
    container_name: ticket-master
    environment: 
      PORT: 8094
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8093:8093
    depends_on:
      - area-db

  twilio:
    build: Backend/Services/Twilio
    container_name: twilio
    environment: 
      PORT: 8094
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8094:8094
    depends_on:
      - area-db

  uber:
    build: Backend/Services/Uber
    container_name: uber
    environment: 
      PORT: 8095
      API_GATEWAY: http://api-gateway:8080/
      DB: postgresql://root:password@area-db:5432/area
      SECRET_KEY: PET
    ports:
      - 8095:8095
    depends_on:
      - area-db

  area-db:
    build: Backend/Database
    container_name: area-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    ports:
      - 5432:5432
    restart: always

  mobile:
    build: Mobile
    container_name: mobile
    environment:
      FLUTTER_HOME: /home/developer/flutter
      PATH: /home/developer/flutter/bin:/home/developer/flutter/bin/cache/dart-sdk/bin:$PATH
    volumes:
      - ./Mobile:/home/developer/app
    ports:
      - 3001:3001
    depends_on:
      - api-gateway

  time-services:
    build: Backend/Services/DateTimeServices
    container_name: time-services
    environment:
      PORT: 8082
      API_GATEWAY: http://api-gateway:8080/
      DATE_TIME_API: http://worldtimeapi.org/api/timezone/Etc/UTC
      DB: postgresql://root:password@area-db:5432/area
      MESSAGE_BROCKER: "http://message-brocker:8084/"
    ports:
      - 8082:8082
    depends_on:
      - area-db
    develop:
      watch:
        - action: sync+restart
          path: ./Backend/Services/DateTimeServices
          target: /app

  discord:
    build: Backend/Services/Discord
    container_name: discord
    environment:
      PORT: 8083
      API_GATEWAY: http://api-gateway:8080/
      MESSAGE_BROCKER: "http://message-brocker:8084/"
      DB: postgresql://root:password@area-db:5432/area
      CLIENT_ID: 1313077002005385236
      CLIENT_SECRET: Ku7K2lQYvws_L-xp7ialrt11weriVHyk
      REDIRECT_WEB: http://localhost:8083/callback
      REDIRECT_MOBILE: http://localhost:8083/mobile-callback
      BOT_TOKEN: MTMxMzA3NzAwMjAwNTM4NTIzNg.GATaQr.oeLw_BYAncCgHUoImxp1YK97Bn_NCgEIWkmDq4
    ports:
      - 8083:8083
    depends_on:
      - area-db
