# version: '3.8'

services:
  client_web:
    build: Frontend
    container_name: client_web
    environment:
      PORT: 8081
    ports:
      - 8081:8081
    volumes:
      - apk-volume:/app/public

  api-gateway:
    build: Backend/ApiGateway
    container_name: api-gateway
    ports:
      - 8080:8080

  message-brocker:
    build: Backend/MessageBrocker
    container_name: message-brocker
    ports:
      - 8084:8084

  cryptomoney:
    build: Backend/Services/CryptoMoney
    container_name: cryptomoney
    ports:
      - 8095:8095

  miro:
    build: Backend/Services/Miro
    container_name: miro
    ports:
      - 8097:8097

  user-services:
    build: Backend/Services/UserServices
    container_name: user-services
    ports:
      - 8085:8085
    depends_on:
      - area-db

  dropbox:
    build: Backend/Services/Dropbox
    container_name: dropbox
    ports:
      - 8096:8096
    depends_on:
      - area-db

  github:
    build: Backend/Services/Github
    container_name: github
    ports:
      - 8086:8086
    depends_on:
      - area-db

  gitlab:
    build: Backend/Services/Gitlab
    container_name: gitlab
    ports:
      - 8087:8087
    depends_on:
      - area-db

  google:
    build: Backend/Services/Google
    container_name: google
    ports:
      - 8088:8088
    depends_on:
      - area-db

  meteo:
    build: Backend/Services/Meteo
    container_name: meteo
    ports:
      - 8089:8089
    depends_on:
      - area-db

  spotify:
    build: Backend/Services/Spotify
    container_name: spotify
    ports:
      - 8091:8091
    depends_on:
      - area-db

  asana:
    build: Backend/Services/Asana
    container_name: asana
    ports:
      - 8092:8092
    depends_on:
      - area-db

  ticket-master:
    build: Backend/Services/TicketMaster
    container_name: ticket-master
    ports:
      - 8093:8093
    depends_on:
      - area-db

  area-db:
    build: Backend/Database
    container_name: area-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    ports:
      - 5432:5432
    restart: always

  time-services:
    build: Backend/Services/DateTimeServices
    container_name: time-services
    ports:
      - 8082:8082
    depends_on:
      - area-db

  discord:
    build: Backend/Services/Discord
    container_name: discord
    ports:
      - 8083:8083
    depends_on:
      - area-db

volumes:
  apk-volume:
