FROM debian:latest

RUN apt-get update && \
    apt-get install -y curl git unzip xz-utils libglu1-mesa openjdk-17-jdk wget ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m developer

USER developer

WORKDIR /home/developer

ENV FLUTTER_HOME=/home/developer/flutter
ENV PATH="$FLUTTER_HOME/bin:$FLUTTER_HOME/bin/cache/dart-sdk/bin:$PATH"
ENV GRADLE_OPTS="-Djava.net.preferIPv4Stack=true"

RUN git clone https://github.com/flutter/flutter.git $FLUTTER_HOME && \
    cd $FLUTTER_HOME && \
    git checkout 3.24.3

RUN flutter doctor -v

ENV ANDROID_HOME=/home/developer/android-sdk
ENV ANDROID_SDK_ROOT=$ANDROID_HOME
ENV PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:${PATH}"

RUN mkdir -p "$ANDROID_HOME/cmdline-tools" && \
    wget -q -O sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip && \
    unzip sdk.zip -d $ANDROID_HOME/cmdline-tools && \
    rm sdk.zip && \
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest && \
    yes | sdkmanager --licenses && \
    sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

WORKDIR /home/developer/app

COPY --chown=developer:developer . /home/developer/app

RUN flutter pub get

CMD ["bash"]