name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Unit Tests
      working-directory: Backend/Services
      run: make tests_run

    - name: Verify Tests
      if: failure()
      run: echo "Unit tests failed" && exit 1
