name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go (if required)
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'

    - name: Run Unit Tests
      working-directory: Backend/Services
      run: make -f Makefile tests_unitaires

    - name: Verify Tests
      if: failure()
      run: echo "Unit tests failed" && exit 1
